version: 0.2
env:
  variables:
    AWS_REGION: "ap-southeast-1"  # Placeholder, will be set dynamically
phases:
  pre_build:
    commands:
      - echo "Installing Python and pip"
      - sudo apt-get update -y
      - sudo apt-get install -y python3 python3-pip zip unzip
      - echo "Installing Packer"
      - curl -o packer.zip https://releases.hashicorp.com/packer/1.11.2/packer_1.11.2_linux_386.zip && unzip packer.zip
      - sudo mv packer /usr/local/bin/packer  # Ensure Packer is accessible globally
      - sudo chmod +x /usr/local/bin/packer   # Make sure it's executable
      - export PATH=$PATH:/usr/local/bin      # Ensure /usr/local/bin is in PATH
      - echo "Validating Packer template"
      - /usr/local/bin/packer validate packer_cis.pkr.hcl
  build:
    commands:
      - /usr/local/bin/packer build -color=false packer_cis.pkr.hcl | tee build.log
  post_build:
    commands:
      - egrep "${AWS_REGION}\:\sami\-" build.log | cut -d' ' -f2 > ami_id.txt
      # Packer doesn't return non-zero status; we must do that if Packer build failed
      - test -s ami_id.txt || exit 1
      - sed -i.bak "s/<<AMI-ID>>/$(cat ami_id.txt)/g" ami_builder_event.json
      - aws events put-events --entries file://ami_builder_event.json
      - echo "build completed on `date`"
artifacts:
  files:
    - ami_builder_event.json
    - build.log
  discard-paths: yes
