# Ensure all packages have been patched
- name: Install necessary packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - git

# - name: upgrade all packages
#   dnf:
#     name: "*"
#     state: latest
